## Acrescentando a extração, validação e limpeza de dados

In [6]:
import pandas as pd
import pandera as pa

In [7]:
#limpeza dos dados não informados e importação do banco de dados
valores_ausentes = ['**','###!','####','****','*****','NUL']
df = pd.read_csv('ocorrencia_2010_2020.csv', sep=';', parse_dates=['ocorrencia_dia'], dayfirst=True, na_values=valores_ausentes)
df.head(10)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
5,39807,39807,INCIDENTE,SALVADOR,BA,NaN,2010-01-06,17:53:00,0
6,40215,40215,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2
9,39711,39711,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10,20:00:00,0

In [10]:
# Fazendo a validação de dados utiizando a biblioteca pandera
schema = pa.DataFrameSchema(
    columns = {
        'codigo_ocorrencia': pa.Column(pa.Int),
        'codigo_ocorrencia2': pa.Column(pa.Int),
        'ocorrencia_classificacao': pa.Column(pa.String),
        'ocorrencia_cidade': pa.Column(pa.String),
        'ocorrencia_uf': pa.Column(pa.String, pa.Check.str_length(2,2), nullable=True),
        'ocorrencia_aerodromo': pa.Column(pa.String, nullable=True),
        'ocorrencia_dia': pa.Column(pa.DateTime),
        'ocorrencia_hora': pa.Column(pa.String, pa.Check.str_matches(r'^([0-1]?[0-9]|[2][0-3]):([0-5][0-9])(:[0-5][0-9])?$'), nullable=True),
        'total_recomendacoes': pa.Column(pa.Int)
    }
)
schema.validate(df)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
...,...,...,...,...,...,...,...,...,...
5747,79804,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0
5748,79757,79757,INCIDENTE GRAVE,LAGOA DA CONFUSÃO,TO,NaN,2020-12-30,18:30:00,0
5749,79802,79802,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2020-12-30,00:54:00,0
5750,79756,79756,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,09:00:00,0
5751,79844,79844,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2020-12-31,13:24:00,0

In [11]:
df.dtypes

codigo_ocorrencia                    int64
codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                  int64
dtype: object

In [33]:
df['ocorrencia_uf']

0    RJ
1    PA
2    RJ
3    MT
4    RS
Name: ocorrencia_uf, dtype: object

In [34]:
df.isna().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  1
ocorrencia_aerodromo        2349
ocorrencia_dia                 0
ocorrencia_hora                1
total_recomendacoes            0
dtype: int64

In [38]:
filtro = df.ocorrencia_uf.isna()
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2227,49474,49474,ACIDENTE,ÁGUAS INTERNACIONAIS,NaN,NaN,2013-09-02,02:54:00,0

In [45]:
# ocorrencias com mais de 10 recomendações
filtro = df.total_recomendacoes > 10
df.loc[filtro,['ocorrencia_cidade','total_recomendacoes']]

         ocorrencia_cidade  total_recomendacoes
63               SÃO PAULO                   11
326         RIO DE JANEIRO                   19
530              SÃO PAULO                   11
727               ITÁPOLIS                   11
872                 RECIFE                   23
884   SÃO JOSÉ DOS PINHAIS                   11
1062            UBERLÂNDIA                   20
1972              BRASÍLIA                   11
2795                SANTOS                   13
3930               VITÓRIA                   12

In [47]:
# ocorrencias cujo classificação == "INCIDENTE GRAVE"
filtro = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2
9,39711,39711,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10,20:00:00,0
29,39709,39709,INCIDENTE GRAVE,CURITIBA,PR,SBBI,2010-01-23,16:36:00,2
35,39487,39487,INCIDENTE GRAVE,PALMAS,TO,SBPJ,2010-01-26,16:50:00,0
...,...,...,...,...,...,...,...,...,...
5741,79754,79754,INCIDENTE GRAVE,NOVA MARINGÁ,MT,NaN,2020-12-28,13:00:00,0
5744,79753,79753,INCIDENTE GRAVE,GOIATUBA,GO,NaN,2020-12-29,12:00:00,0
5746,79769,79769,INCIDENTE GRAVE,MANOEL URBANO,AC,SIMB,2020-12-29,18:30:00,0
5748,79757,79757,INCIDENTE GRAVE,LAGOA DA CONFUSÃO,TO,NaN,2020-12-30,18:30:00,0
5750,79756,79756,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,09:00:00,0

In [52]:
# ocorrencias cujo classificação == "INCIDENTE GRAVE" e estado == "SP"
filtro1 = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
136,40270,40270,INCIDENTE GRAVE,PIRASSUNUNGA,SP,SDPY,2010-04-15,20:15:00,0
171,40620,40620,INCIDENTE GRAVE,GUARULHOS,SP,SBGR,2010-05-06,15:50:00,0
219,41411,41411,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2010-06-08,19:30:00,2
297,42289,42289,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2010-07-29,20:06:00,0
314,42323,42323,INCIDENTE GRAVE,SÃO JOSÉ DO RIO PRETO,SP,SBSR,2010-08-05,12:01:00,0
...,...,...,...,...,...,...,...,...,...
5591,79540,79540,INCIDENTE GRAVE,SÃO PAULO,SP,NaN,2020-09-12,13:10:00,0
5610,79566,79566,INCIDENTE GRAVE,REGENTE FEIJÓ,SP,SDYJ,2020-09-27,19:33:00,0
5704,79739,79739,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2020-12-03,14:42:00,0
5705,79705,79705,INCIDENTE GRAVE,SOROCABA,SP,SDCO,2020-12-04,15:30:00,0
5715,79718,79718,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2020-12-11,13:50:00,0

In [53]:
# ocorrencias cujo classificação == "INCIDENTE GRAVE" ou estado == "SP"
filtro1 = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 | filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2
9,39711,39711,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10,20:00:00,0
11,40069,40069,ACIDENTE,SÃO PAULO,SP,SBMT,2010-01-10,14:50:00,8
16,39809,39809,INCIDENTE,SÃO PAULO,SP,NaN,2010-01-15,15:00:00,0
...,...,...,...,...,...,...,...,...,...
5744,79753,79753,INCIDENTE GRAVE,GOIATUBA,GO,NaN,2020-12-29,12:00:00,0
5746,79769,79769,INCIDENTE GRAVE,MANOEL URBANO,AC,SIMB,2020-12-29,18:30:00,0
5747,79804,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0
5748,79757,79757,INCIDENTE GRAVE,LAGOA DA CONFUSÃO,TO,NaN,2020-12-30,18:30:00,0
5750,79756,79756,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,09:00:00,0

In [57]:
# ocorrencias cujo classificação == "INCIDENTE GRAVE" ou classificação == "INCIDENTE" e estado == "SP"
# não esquecer de separar com parênteses
# funcao 'isin' funciona como (condicao1 | condicao2)
filtro1 = df.ocorrencia_classificacao.isin(['INCIDENTE GRAVE','INCIDENTE'])
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
16,39809,39809,INCIDENTE,SÃO PAULO,SP,NaN,2010-01-15,15:00:00,0
18,39828,39828,INCIDENTE,SANTOS,SP,NaN,2010-01-15,17:45:00,0
26,39847,39847,INCIDENTE,SOROCABA,SP,NaN,2010-01-20,13:10:00,0
27,39768,39768,INCIDENTE,CAMPINAS,SP,NaN,2010-01-21,20:45:00,0
33,39848,39848,INCIDENTE,GUARULHOS,SP,SBGR,2010-01-25,17:05:00,0
...,...,...,...,...,...,...,...,...,...
5704,79739,79739,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2020-12-03,14:42:00,0
5705,79705,79705,INCIDENTE GRAVE,SOROCABA,SP,SDCO,2020-12-04,15:30:00,0
5715,79718,79718,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2020-12-11,13:50:00,0
5742,79800,79800,INCIDENTE,SÃO PAULO,SP,SBMT,2020-12-28,10:15:00,0
5747,79804,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0

In [60]:
# ocorrências cujo cidade começa com a letra C
filtro = df.ocorrencia_cidade.str[0] == 'C'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
6,40215,40215,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2
15,39315,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0
20,40310,40310,INCIDENTE,CRUZEIRO DO SUL,AC,SBCZ,2010-01-18,19:32:00,0
...,...,...,...,...,...,...,...,...,...
5661,79649,79649,INCIDENTE,CAMPINAS,SP,SBKP,2020-11-04,22:39:00,0
5663,79652,79652,INCIDENTE,CONFINS,MG,SBCF,2020-11-06,14:20:00,0
5680,79683,79683,INCIDENTE,CRUZEIRO DO SUL,AC,SBCZ,2020-11-16,22:00:00,0
5696,79692,79692,ACIDENTE,CATANDUVA,SP,SDCD,2020-11-28,12:50:00,0
5747,79804,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0

In [63]:
# ocorrências cujo cidade contendo (em qualquer posição) os caracteres 'MA'
filtro = df.ocorrencia_cidade.str.contains('MA')
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3
13,39507,39507,ACIDENTE,PRIMAVERA DO LESTE,MT,NaN,2010-01-11,17:00:00,2
15,39315,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0
35,39487,39487,INCIDENTE GRAVE,PALMAS,TO,SBPJ,2010-01-26,16:50:00,0
78,39916,39916,INCIDENTE GRAVE,MANAUS,AM,SBEG,2010-03-07,19:35:00,2
...,...,...,...,...,...,...,...,...,...
5732,79745,79745,INCIDENTE,MARABÁ,PA,SBMA,2020-12-21,08:47:00,0
5739,79749,79749,ACIDENTE,MARITUBA,PA,NaN,2020-12-26,12:05:00,0
5741,79754,79754,INCIDENTE GRAVE,NOVA MARINGÁ,MT,NaN,2020-12-28,13:00:00,0
5745,79755,79755,ACIDENTE,MATO RICO,PR,NaN,2020-12-29,10:30:00,0
5746,79769,79769,INCIDENTE GRAVE,MANOEL URBANO,AC,SIMB,2020-12-29,18:30:00,0

In [64]:
# ocorrências do ano de 2015
filtro = df.ocorrencia_dia.dt.year == 2015
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2996,52992,52992,INCIDENTE GRAVE,SALVADOR,BA,SBSV,2015-01-01,11:40:00,3
2997,52979,52979,ACIDENTE,IVINHEMA,MS,NaN,2015-01-02,14:50:00,0
2998,53073,53073,INCIDENTE,TEFÉ,AM,SBTF,2015-01-02,16:28:00,0
2999,53074,53074,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-01-02,20:34:00,0
3000,52976,52976,ACIDENTE,TOLEDO,PR,SBTD,2015-01-04,22:04:00,6
...,...,...,...,...,...,...,...,...,...
3462,60632,60632,INCIDENTE GRAVE,ITABERÁ,SP,NaN,2015-12-24,14:00:00,0
3463,60600,60600,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0
3464,60642,60642,INCIDENTE,SÃO FRANCISCO DO SUL,SC,SSSS,2015-12-26,16:00:00,0
3465,60631,60631,ACIDENTE,MAÇAMBARÁ,RS,NaN,2015-12-28,19:00:00,2
3466,60649,60649,ACIDENTE,PORTO BELO,SC,SDEN,2015-12-31,14:00:00,0

In [65]:
# ocorrências do ano de 2015 e mês 12
filtro = (df.ocorrencia_dia.dt.year == 2015) & (df.ocorrencia_dia.dt.month == 12)
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
3428,53573,53573,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-01,02:48:00,0
3429,60601,60601,INCIDENTE,PALMAS,TO,SBPJ,2015-12-01,16:05:00,0
3430,53634,53634,INCIDENTE,PALMAS,TO,SBPJ,2015-12-02,17:45:00,0
3431,53636,53636,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-12-02,17:42:00,0
3432,53575,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0
3433,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0
3434,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3
3435,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1
3436,53628,53628,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1
3437,53629,53629,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0
3438,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0
3439,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0
3440,53627,53627,INCIDENTE,TERESINA,PI,SBTE,2015-12-12,19:05:00,0
3441,60604,60604,INCIDENTE,GOIÂNIA,GO,SBGO,2015-12-12,14:34:00,0
3442,60611,60611,INCIDENTE,SÃO PAULO,SP,SBSP,2015-12-12,15:30:00,0
3443,60613,60613,ACIDENTE,JUSCIMEIRA,MT,SWMO,2015-12-12,08:31:00,0
3444,60629,60629,ACIDENTE,RIO GRANDE,RS,NaN,2015-12-12,10:40:00,0
3445,53630,53630,INCIDENTE,MARÍLIA,SP,SBML,2015-12-13,13:50:00,0
3446,60603,60603,INCIDENTE,LONDRINA,PR,SBLO,2015-12-13,17:46:00,0
3447,60612,60612,ACIDENTE,BENTO GONÇALVES,RS,SSBG,2015-12-13,20:30:00,0
3448,60783,60783,ACIDENTE,LAGES,SC,NaN,2015-12-13,14:00:00,3
3449,53639,53639,INCIDENTE,LOUVEIRA,SP,SDAM,2015-12-15,14:20:00,0
3450,60609,60609,INCIDENTE GRAVE,ARAGUAÍNA,TO,SWGN,2015-12-15,13:00:00,0
3451,60616,60616,ACIDENTE,PALOTINA,PR,NaN,2015-12-15,20:30:00,0
3452,60620,60620,ACIDENTE,RIO DE JANEIRO,RJ,SBJR,2015-12-15,16:50:00,4
3453,60645,60645,ACIDENTE,SERTÃOZINHO,SP,NaN,2015-12-15,13:00:00,0
3454,60608,60608,INCIDENTE,BELO HORIZONTE,MG,SBPR,2015-12-16,10:38:00,0
3455,60625,60625,ACIDENTE,ITÁPOLIS,SP,SDIO,2015-12-17,21:30:00,1
3456,60605,60605,INCIDENTE,UBERLÂNDIA,MG,SBUL,2015-12-18,10:25:00,0
3457,60610,60610,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-12-18,18:45:00,0
3458,60602,60602,INCIDENTE,RIBEIRÃO PRETO,SP,SBRP,2015-12-22,06:27:00,0
3459,60615,60615,INCIDENTE,SÃO PAULO,SP,SBMT,2015-12-22,13:07:00,0
3460,60640,60640,INCIDENTE,CASCAVEL,PR,SBCA,2015-12-23,13:20:00,0
3461,60641,60641,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-23,15:53:00,0
3462,60632,60632,INCIDENTE GRAVE,ITABERÁ,SP,NaN,2015-12-24,14:00:00,0
3463,60600,60600,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0
3464,60642,60642,INCIDENTE,SÃO FRANCISCO DO SUL,SC,SSSS,2015-12-26,16:00:00,0
3465,60631,60631,ACIDENTE,MAÇAMBARÁ,RS,NaN,2015-12-28,19:00:00,2
3466,60649,60649,ACIDENTE,PORTO BELO,SC,SDEN,2015-12-31,14:00:00,0

In [67]:
df['ocorrencia_dia_hora'] = pd.to_datetime(df.ocorrencia_dia.astype(str) + ' ' + df.ocorrencia_hora)

In [68]:
df.head()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0,2010-01-03 12:00:00
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0,2010-01-03 11:05:00
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0,2010-01-03 03:00:00
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0,2010-01-04 17:30:00
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0,2010-01-05 19:25:00

In [69]:
filtro1 = df.ocorrencia_dia_hora >= '2010-01-03 11:00:00'
filtro2 = df.ocorrencia_dia_hora <= '2010-01-08 13:00:00'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0,2010-01-03 12:00:00
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0,2010-01-03 11:05:00
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0,2010-01-04 17:30:00
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0,2010-01-05 19:25:00
5,39807,39807,INCIDENTE,SALVADOR,BA,NaN,2010-01-06,17:53:00,0,2010-01-06 17:53:00
6,40215,40215,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0,2010-01-07 18:40:00

In [72]:
# ocorrencias de 2015 e mes 3
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 3
df201503 = df.loc[filtro1 & filtro2]

df201503

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
3086,53183,53183,ACIDENTE,AMAPORÃ,PR,NaN,2015-03-02,23:00:00,0,2015-03-02 23:00:00
3087,53120,53120,ACIDENTE,CHAVES,PA,SNXW,2015-03-04,13:30:00,0,2015-03-04 13:30:00
3088,53109,53109,ACIDENTE,CAMPO GRANDE,MS,SSIE,2015-03-05,13:50:00,0,2015-03-05 13:50:00
3089,53112,53112,ACIDENTE,MOGI GUAÇU,SP,NaN,2015-03-06,21:00:00,0,2015-03-06 21:00:00
3090,53152,53152,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBRJ,2015-03-10,11:30:00,2,2015-03-10 11:30:00
3091,53167,53167,INCIDENTE,MARABÁ,PA,SBMA,2015-03-10,17:33:00,0,2015-03-10 17:33:00
3092,53596,53596,INCIDENTE,ITAPEMA,SC,NaN,2015-03-10,21:35:00,0,2015-03-10 21:35:00
3093,53149,53149,ACIDENTE,TABATINGA,AM,SBTT,2015-03-11,23:25:00,0,2015-03-11 23:25:00
3094,53148,53148,ACIDENTE,ARARAS,SP,SDEH,2015-03-12,12:40:00,0,2015-03-12 12:40:00
3095,53153,53153,INCIDENTE,PORTO ALEGRE,RS,SBPA,2015-03-13,15:45:00,0,2015-03-13 15:45:00
3096,53154,53154,INCIDENTE,SOROCABA,SP,SDCO,2015-03-13,14:40:00,0,2015-03-13 14:40:00
3097,53238,53238,INCIDENTE,SERRA,ES,NaN,2015-03-13,11:30:00,0,2015-03-13 11:30:00
3098,53189,53189,INCIDENTE,CONFINS,MG,SBCF,2015-03-14,07:20:00,0,2015-03-14 07:20:00
3099,53193,53193,ACIDENTE,CANARANA,MT,NaN,2015-03-14,18:00:00,0,2015-03-14 18:00:00
3100,53164,53164,ACIDENTE,PRINCESA ISABEL,PB,NaN,2015-03-15,18:30:00,0,2015-03-15 18:30:00
3101,53151,53151,INCIDENTE GRAVE,MAUÉS,AM,SWMW,2015-03-16,18:07:00,1,2015-03-16 18:07:00
3102,53168,53168,INCIDENTE,PARÁ DE MINAS,MG,SNPA,2015-03-16,21:05:00,0,2015-03-16 21:05:00
3103,53169,53169,INCIDENTE,BELÉM,PA,SBBE,2015-03-19,03:25:00,0,2015-03-19 03:25:00
3104,53165,53165,INCIDENTE GRAVE,SÃO DESIDÉRIO,BA,NaN,2015-03-20,14:35:00,0,2015-03-20 14:35:00
3105,53188,53188,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2015-03-20,21:00:00,0,2015-03-20 21:00:00
3106,53184,53184,ACIDENTE,PORTO UNIÃO,SC,NaN,2015-03-22,13:44:00,0,2015-03-22 13:44:00
3107,53178,53178,ACIDENTE,DIAMANTINO,MT,NaN,2015-03-23,17:15:00,0,2015-03-23 17:15:00
3108,53182,53182,ACIDENTE,SANTA LUZIA,MA,NaN,2015-03-23,20:40:00,0,2015-03-23 20:40:00
3109,53166,53166,INCIDENTE GRAVE,RIACHÃO DAS NEVES,BA,NaN,2015-03-24,14:45:00,0,2015-03-24 14:45:00
3110,53170,53170,INCIDENTE,CONFINS,MG,SBCF,2015-03-24,17:57:00,0,2015-03-24 17:57:00
3111,53185,53185,INCIDENTE,CURITIBA,PR,SBCT,2015-03-24,23:01:00,0,2015-03-24 23:01:00
3112,53412,53412,INCIDENTE GRAVE,MACAÉ,RJ,NaN,2015-03-24,16:35:00,0,2015-03-24 16:35:00
3113,53194,53194,ACIDENTE,GUARACIABA DO NORTE,CE,SWBE,2015-03-26,20:30:00,0,2015-03-26 20:30:00
3114,53186,53186,INCIDENTE,BRASÍLIA,DF,NaN,2015-03-27,14:55:00,0,2015-03-27 14:55:00
3115,53179,53179,ACIDENTE,CAIAPÔNIA,GO,NaN,2015-03-28,10:30:00,0,2015-03-28 10:30:00
3116,53180,53180,ACIDENTE,ARAGUARI,MG,NaN,2015-03-28,18:52:00,0,2015-03-28 18:52:00
3117,53190,53190,INCIDENTE,CAMPINAS,SP,SBKP,2015-03-28,16:26:00,0,2015-03-28 16:26:00
3118,53212,53212,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-03-28,17:32:00,0,2015-03-28 17:32:00
3119,53213,53213,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-03-28,15:51:00,0,2015-03-28 15:51:00
3120,53181,53181,ACIDENTE,COLÍDER,MT,NaN,2015-03-29,20:17:00,0,2015-03-29 20:17:00
3121,53187,53187,INCIDENTE,JOINVILLE,SC,SBJV,2015-03-29,18:36:00,0,2015-03-29 18:36:00
3122,53211,53211,INCIDENTE,BAURU,SP,SBBU,2015-03-30,19:40:00,0,2015-03-30 19:40:00

In [73]:
df201503.count()

codigo_ocorrencia           37
codigo_ocorrencia2          37
ocorrencia_classificacao    37
ocorrencia_cidade           37
ocorrencia_uf               37
ocorrencia_aerodromo        21
ocorrencia_dia              37
ocorrencia_hora             37
total_recomendacoes         37
ocorrencia_dia_hora         37
dtype: int64

In [84]:
df201503.groupby(['ocorrencia_classificacao']).codigo_ocorrencia.count()

ocorrencia_classificacao
ACIDENTE           15
INCIDENTE          17
INCIDENTE GRAVE     5
Name: codigo_ocorrencia, dtype: int64

In [85]:
df201503.groupby(['ocorrencia_classificacao']).ocorrencia_aerodromo.count()
#neste caso para contar por uma coluna que contém nulo é equivocado, pois pode aprensentar informações não verdadeiras

ocorrencia_classificacao
ACIDENTE            5
INCIDENTE          14
INCIDENTE GRAVE     2
Name: ocorrencia_aerodromo, dtype: int64

In [86]:
df201503.groupby(['ocorrencia_classificacao']).size()

ocorrencia_classificacao
ACIDENTE           15
INCIDENTE          17
INCIDENTE GRAVE     5
dtype: int64

In [87]:
# Agrupando por ordem crescente
df201503.groupby(['ocorrencia_classificacao']).size().sort_values()

ocorrencia_classificacao
INCIDENTE GRAVE     5
ACIDENTE           15
INCIDENTE          17
dtype: int64

In [89]:
# Agrupando por ordem decrescente
df201503.groupby(['ocorrencia_classificacao']).size().sort_values(ascending=False)

ocorrencia_classificacao
INCIDENTE          17
ACIDENTE           15
INCIDENTE GRAVE     5
dtype: int64

In [93]:
# Filtro pegando região sudeste e no ano de 2010
filtro1 = df.ocorrencia_dia.dt.year == 2010
filtro2 = df.ocorrencia_uf.isin(['SP', 'MG', 'ES', 'RJ'])
dfsudeste2010 = df.loc[filtro1 & filtro2]
dfsudeste2010

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0,2010-01-03 12:00:00
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0,2010-01-03 03:00:00
9,39711,39711,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10,20:00:00,0,2010-01-10 20:00:00
11,40069,40069,ACIDENTE,SÃO PAULO,SP,SBMT,2010-01-10,14:50:00,8,2010-01-10 14:50:00
16,39809,39809,INCIDENTE,SÃO PAULO,SP,NaN,2010-01-15,15:00:00,0,2010-01-15 15:00:00
...,...,...,...,...,...,...,...,...,...,...
541,43722,43722,ACIDENTE,CAJOBI,SP,NaN,2010-12-23,11:00:00,0,2010-12-23 11:00:00
544,43548,43548,INCIDENTE,SÃO PAULO,SP,SBSP,2010-12-26,22:10:00,0,2010-12-26 22:10:00
548,43724,43724,ACIDENTE,COSMÓPOLIS,SP,NaN,2010-12-29,12:00:00,0,2010-12-29 12:00:00
550,43730,43730,INCIDENTE,VITÓRIA,ES,NaN,2010-12-30,18:10:00,0,2010-12-30 18:10:00
551,43975,43975,INCIDENTE,ARRAIAL DO CABO,RJ,NaN,2010-12-30,14:28:00,0,2010-12-30 14:28:00

In [94]:
dfsudeste2010.groupby(['ocorrencia_classificacao']).size()

ocorrencia_classificacao
ACIDENTE            40
INCIDENTE          170
INCIDENTE GRAVE     18
dtype: int64

In [100]:
dfsudeste2010.count()

codigo_ocorrencia           228
codigo_ocorrencia2          228
ocorrencia_classificacao    228
ocorrencia_cidade           228
ocorrencia_uf               228
ocorrencia_aerodromo        127
ocorrencia_dia              228
ocorrencia_hora             228
total_recomendacoes         228
ocorrencia_dia_hora         228
dtype: int64

In [110]:
dfsudeste2010.groupby(['ocorrencia_classificacao','ocorrencia_uf']).size()

ocorrencia_classificacao  ocorrencia_uf
ACIDENTE                  MG                7
                          RJ                9
                          SP               24
INCIDENTE                 ES                5
                          MG               39
                          RJ               52
                          SP               74
INCIDENTE GRAVE           MG                5
                          RJ                4
                          SP                9
dtype: int64

In [120]:
filtro = dfsudeste2010.ocorrencia_cidade == 'RIO DE JANEIRO'
dfsudeste2010.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0,2010-01-03 12:00:00
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0,2010-01-03 03:00:00
19,44575,44575,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-01-17,12:27:00,0,2010-01-17 12:27:00
23,40311,40311,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-19,13:20:00,0,2010-01-19 13:20:00
24,41577,41577,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-19,12:16:00,0,2010-01-19 12:16:00
30,39849,39849,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-01-23,03:30:00,0,2010-01-23 03:30:00
39,40617,40617,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-01-27,20:06:00,0,2010-01-27 20:06:00
49,39295,39295,ACIDENTE,RIO DE JANEIRO,RJ,NaN,2010-02-06,21:09:00,0,2010-02-06 21:09:00
71,39987,39987,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-02-24,19:37:00,0,2010-02-24 19:37:00
101,40210,40210,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-03-20,20:02:00,0,2010-03-20 20:02:00
105,40209,40209,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-03-21,13:46:00,0,2010-03-21 13:46:00
107,40330,40330,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-03-24,11:35:00,0,2010-03-24 11:35:00
119,40190,40190,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-04-06,02:35:00,3,2010-04-06 02:35:00
139,40294,40294,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-04-16,20:00:00,0,2010-04-16 20:00:00
144,40293,40293,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-04-18,16:23:00,0,2010-04-18 16:23:00
154,40581,40581,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-04-21,13:20:00,0,2010-04-21 13:20:00
164,40774,40774,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-05-01,02:10:00,0,2010-05-01 02:10:00
185,41573,41573,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-05-13,16:10:00,0,2010-05-13 16:10:00
223,41591,41591,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-06-10,17:30:00,0,2010-06-10 17:30:00
240,41678,41678,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-06-19,19:05:00,0,2010-06-19 19:05:00
242,42011,42011,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-06-19,13:16:00,0,2010-06-19 13:16:00
248,41729,41729,ACIDENTE,RIO DE JANEIRO,RJ,NaN,2010-06-25,13:05:00,0,2010-06-25 13:05:00
274,41750,41750,ACIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-07-12,19:53:00,3,2010-07-12 19:53:00
284,42067,42067,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-07-20,12:41:00,0,2010-07-20 12:41:00
296,42634,42634,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-07-28,10:05:00,0,2010-07-28 10:05:00
298,42436,42436,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-07-29,19:12:00,0,2010-07-29 19:12:00
300,42619,42619,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-07-30,09:24:00,0,2010-07-30 09:24:00
309,42443,42443,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-08-04,13:27:00,0,2010-08-04 13:27:00
319,42284,42284,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2010-08-10,12:30:00,0,2010-08-10 12:30:00
326,42250,42250,ACIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-08-12,12:26:00,19,2010-08-12 12:26:00
335,42456,42456,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-08-21,16:35:00,0,2010-08-21 16:35:00
336,42740,42740,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-08-21,13:25:00,0,2010-08-21 13:25:00
341,42486,42486,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-08-23,23:55:00,0,2010-08-23 23:55:00
352,42603,42603,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-08-27,13:27:00,0,2010-08-27 13:27:00
359,42598,42598,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-08-31,12:35:00,0,2010-08-31 12:35:00
375,42714,42714,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,NaN,2010-09-11,15:30:00,0,2010-09-11 15:30:00
377,42868,42868,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-09-11,20:30:00,0,2010-09-11 20:30:00
386,43064,43064,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-09-15,17:54:00,0,2010-09-15 17:54:00
388,42880,42880,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBJR,2010-09-17,13:55:00,0,2010-09-17 13:55:00
389,42882,42882,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBJR,2010-09-17,18:46:00,0,2010-09-17 18:46:00
427,43578,43578,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-10-04,12:30:00,0,2010-10-04 12:30:00
432,43033,43033,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-10-05,21:46:00,0,2010-10-05 21:46:00
456,43699,43699,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-10-23,17:43:00,0,2010-10-23 17:43:00
494,43283,43283,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2010-11-20,13:02:00,0,2010-11-20 13:02:00
526,43527,43527,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-12-12,19:00:00,0,2010-12-12 19:00:00
527,43462,43462,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBGL,2010-12-13,11:00:00,0,2010-12-13 11:00:00
536,43921,43921,ACIDENTE,RIO DE JANEIRO,RJ,NaN,2010-12-18,13:15:00,0,2010-12-18 13:15:00

In [125]:
dfsudeste2010.groupby(['ocorrencia_aerodromo'], dropna=False).total_recomendacoes.sum().sort_values(ascending=False)

ocorrencia_aerodromo
NaN     45
SBMT    27
SBRJ    19
SBBP     9
SBJD     7
SBGL     3
SBJR     3
SDOI     1
SBPR     1
SBIP     0
SBSR     0
SNXT     0
SNDV     0
SNDT     0
SDPY     0
SDPW     0
SBBH     0
SDAM     0
SBVT     0
SBUR     0
SBUL     0
SBSP     0
SBGR     0
SBSJ     0
SBRP     0
SBBU     0
SBAQ     0
SBPC     0
SBCF     0
SBML     0
SBMK     0
SBME     0
SBKP     0
SBAE     0
Name: total_recomendacoes, dtype: int64

In [129]:
dfsudeste2010.groupby(['ocorrencia_cidade']).total_recomendacoes.sum()

ocorrencia_cidade
AMERICANA                 0
ARARAQUARA                0
ARAÇATUBA                 0
AREALVA                   0
ARRAIAL DO CABO           0
BAURU                     0
BEBEDOURO                 0
BELO HORIZONTE            2
BOCAINA                   0
BOITUVA                   1
BOM JESUS DO AMPARO       0
BOM JESUS DO GALHO        1
BRAGANÇA PAULISTA         9
BROTAS                    0
CAJOBI                    0
CAMANDUCAIA               9
CAMPINAS                  0
CAMPOS DOS GOYTACAZES     0
CASIMIRO DE ABREU         0
CONFINS                   0
COROMANDEL                0
COSMÓPOLIS                0
DIAMANTINA                0
DIVINÓPOLIS               0
GUARULHOS                 0
IPATINGA                  0
IPERÓ                     3
ITANHAÉM                  1
ITÁPOLIS                  0
JUIZ DE FORA              0
JUNDIAÍ                   7
LINHARES                  0
MACAÉ                     0
MANGARATIBA               0
MARÍLIA                   0
MONTES CLAROS             0
NOVO HORIZONTE            3
OLÍMPIA                   0
PARÁ DE MINAS             0
PENÁPOLIS                 0
PIACATU                   0
PIRACICABA                0
PIRASSUNUNGA              0
POUSO ALEGRE              0
POÇOS DE CALDAS           0
RESENDE                   8
RIBEIRÃO PRETO            0
RIO DE JANEIRO           25
SANTOS                    0
SERRA NEGRA               0
SOROCABA                  0
SÃO BERNARDO DO CAMPO     2
SÃO JOSÉ DO RIO PRETO     0
SÃO JOSÉ DOS CAMPOS       0
SÃO PAULO                41
TIMÓTEO                   3
UBERABA                   0
UBERLÂNDIA                0
VITÓRIA                   0
Name: total_recomendacoes, dtype: int64

In [131]:
# Com recomendações acima de zero
filtro = dfsudeste2010.total_recomendacoes > 0
dfsudeste2010.loc[filtro].groupby(['ocorrencia_cidade']).total_recomendacoes.sum().sort_values(ascending=False)

ocorrencia_cidade
SÃO PAULO                41
RIO DE JANEIRO           25
BRAGANÇA PAULISTA         9
CAMANDUCAIA               9
RESENDE                   8
JUNDIAÍ                   7
IPERÓ                     3
NOVO HORIZONTE            3
TIMÓTEO                   3
BELO HORIZONTE            2
SÃO BERNARDO DO CAMPO     2
BOITUVA                   1
BOM JESUS DO GALHO        1
ITANHAÉM                  1
Name: total_recomendacoes, dtype: int64